# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
