# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('longitude', models.BigIntegerField()),
                ('latitude', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.BigIntegerField()),
                ('latitude', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='season',
        ),
        migrations.AddField(
            model_name='product',
            name='fall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='spring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='summer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='winter',
            field=models.BooleanField(default=False),
        ),
    ]
