# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171022_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='market',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='query',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='query',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
