# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171023_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='address',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='query',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='query',
            name='longitude',
        ),
        migrations.AddField(
            model_name='query',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
    ]
