# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171023_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
