# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_query_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='market',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.AddField(
            model_name='market',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='market',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Market'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Baked Goods', 'Baked Goods'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Jams, Jellies, and Syrups', 'Jams, Jellies, and Syrups'), ('Meat', 'Meat'), ('Sauces', 'Sauces'), ('Noodles and Grains', 'Noodles and Grains')], max_length=50),
        ),
    ]
